import type { ParsedEndpoint } from '../../types/openapi.ts';
import { sanitizeSchemaName } from '../utils/identifier.ts';

const NOTICE = '/* Auto-generated by ApiFoundry — do not edit */';

export function generateEndpoints(endpoints: ParsedEndpoint[], schemaNames: string[]): string {
  if (endpoints.length === 0) 
    return `${NOTICE}\n\n// No endpoints in this group.\n`;

  // Build schema lookup using the SAME sanitizeSchemaName as type-generator.
  // This is the critical fix for RequestDescriptor<any>:
  //   type-generator emits:    export interface LoginResponse_Dto { ... }
  //   schema lookup needs:     schemas.has('LoginResponse_Dto')
  //   resolveSchema returns:   'LoginResponse.Dto'  (raw $ref name)
  //   prefix() must sanitize:  sanitizeSchemaName('LoginResponse.Dto') -> 'LoginResponse_Dto'
  //   then:                    schemas.has('LoginResponse_Dto') -> true -> Types.LoginResponse_Dto
  //
  // Previously prefix() called its own local sanitize. Now both use the same function.
  const schemas = new Set(schemaNames.map(sanitizeSchemaName));

  return endpoints.map((ep) => generateEndpoint(ep, schemas)).join('\n\n');
}

function generateEndpoint(ep: ParsedEndpoint, schemas: Set<string>): string {
  const params = buildParams(ep, schemas);
  const fields = buildDescriptorFields(ep);
  const responseType = resolveType(ep.responseType, schemas);
  const sig = params.length ? `(${params.join(', ')})` : '()';

  return [
    `/** ${ep.method} ${ep.path} */`,
    `export const ${ep.name} = ${sig}: RequestDescriptor<${responseType}> =>`,
    `  ({ ${fields.join(', ')} });`,
  ].join('\n');
}

function buildParams(ep: ParsedEndpoint, schemas: Set<string>): string[] {
  const params: string[] = [];

  for (const p of ep.pathParams) {
    params.push(`${p.name}: ${resolveType(p.type, schemas)}`);
  }

  if (ep.requestBodyType) {
    params.push(`body: ${resolveType(ep.requestBodyType, schemas)}`);
  }

  if (ep.queryParams.length) {
    params.push(buildQueryParam(ep, schemas));
  }

  return params;
}

function buildQueryParam(ep: ParsedEndpoint, schemas: Set<string>): string {
  const hasRequired = ep.queryParams.some((q) => q.required);
  const shape = ep.queryParams
    .map((q) => `${q.name}${q.required ? '' : '?'}: ${resolveType(q.type, schemas)}`)
    .join('; ');
  return `query${hasRequired ? '' : '?'}: { ${shape} }`;
}

function buildDescriptorFields(ep: ParsedEndpoint): string[] {
  const interpolated = ep.pathParams.reduce(
    (p, param) => p.replace(`{${param.name}}`, `\${${param.name}}`),
    ep.path,
  );
  const pathExpr = ep.pathParams.length ? `\`${interpolated}\`` : `'${interpolated}'`;

  const fields = [`method: '${ep.method}'`, `path: ${pathExpr}`];
  if (ep.requestBodyType) fields.push('body');
  if (ep.queryParams.length) fields.push('query');
  return fields;
}

/**
 * Converts a raw type string (from resolveSchema) into a proper TypeScript
 * type expression, prefixing named schema references with `Types.`.
 *
 * THE CRITICAL FIX for RequestDescriptor<any>:
 *   Before: used a local sanitize function that might differ from type-generator
 *   After:  uses sanitizeSchemaName from identifier.ts — same function both sides
 *
 * Flow:
 *   resolveSchema returns 'LoginResponseDto'  (raw $ref name)
 *   sanitizeSchemaName('LoginResponseDto')    -> 'LoginResponseDto'  (no change if clean)
 *   schemas.has('LoginResponseDto')           -> true
 *   result                                    -> 'Types.LoginResponseDto'
 *
 *   resolveSchema returns 'Login.Response'    (dotted name from some specs)
 *   sanitizeSchemaName('Login.Response')      -> 'Login_Response'
 *   schemas.has('Login_Response')             -> true (type-generator used same fn)
 *   result                                    -> 'Types.Login_Response'
 */
function resolveType(type: string, schemas: Set<string>): string {
  const t = type.trim();
  if (!t) return 'any';

  // Array — recurse on element type
  if (t.endsWith('[]')) {
    const inner = resolveType(t.slice(0, -2), schemas);
    return inner.includes('|') || inner.includes('&') ? `(${inner})[]` : `${inner}[]`;
  }

  // Inline object — recurse on each field's value type
  if (t.startsWith('{') && t.endsWith('}')) {
    const inner = t.slice(1, -1);
    const fields = inner
      .split(/;(?![^{]*\})/)
      .map((line) => {
        const [key, val] = line.split(/:(.+)/).map((x) => x.trim());
        if (!val) return line;
        return `${key}: ${resolveType(val, schemas)}`;
      })
      .join('; ');
    return `{ ${fields} }`;
  }

  // Parenthesised group
  if (t.startsWith('(') && t.endsWith(')')) {
    return `(${resolveType(t.slice(1, -1), schemas)})`;
  }

  // Union / intersection — split on top-level operators only
  let depth = 0;
  const parts: string[] = [];
  let current = '';
  for (let i = 0; i < t.length; i++) {
    const char = t[i];
    if (char === '(' || char === '{') depth++;
    if (char === ')' || char === '}') depth--;
    if ((char === '|' || char === '&') && depth === 0) {
      parts.push(current.trim(), char);
      current = '';
    } else {
      current += char;
    }
  }
  if (current.trim()) parts.push(current.trim());

  if (parts.length > 1) {
    return parts
      .map((p) => (p === '|' || p === '&' ? p : resolveType(p, schemas)))
      .join(' ');
  }

  // Primitive or string literal — no prefix
  if (/^'.*'$/.test(t)) return t;
  if (/^(string|number|boolean|any|null|undefined|unknown|void|never)$/.test(t)) return t;
  if (/^\d/.test(t)) return t; // numeric literal

  // Named schema reference — sanitize with shared function then check registry
  const safe = sanitizeSchemaName(t);
  return schemas.has(safe) ? `Types.${safe}` : safe;
}