import type { ParsedEndpoint } from '../../types/openapi.ts';

const NOTICE = '/* Auto-generated by ApiFoundry — do not edit */';

export function generateEndpoints(endpoints: ParsedEndpoint[], schemaNames: string[]): string {
  if (endpoints.length === 0) return `${NOTICE}\n\n// No endpoints in this group.\n`;
  const schemas = new Set(schemaNames);
  return endpoints.map((ep) => generateEndpoint(ep, schemas)).join('\n\n');
}

function generateEndpoint(ep: ParsedEndpoint, schemas: Set<string>): string {
  const params = buildParams(ep, schemas);
  const fields = buildDescriptorFields(ep);
  const responseType = prefix(ep.responseType, schemas);
  const sig = params.length ? `(${params.join(', ')})` : '()';

  return [
    `/** ${ep.method} ${ep.path} */`,
    `export const ${ep.name} = ${sig}: RequestDescriptor<${responseType}> =>`,
    `  ({ ${fields.join(', ')} });`,
  ].join('\n');
}

function buildParams(ep: ParsedEndpoint, schemas: Set<string>): string[] {
  const params: string[] = [];
  for (const p of ep.pathParams) params.push(`${p.name}: ${prefix(p.type, schemas)}`);
  if (ep.requestBodyType)    params.push(`body: ${prefix(ep.requestBodyType, schemas)}`);
  if (ep.queryParams.length) params.push(buildQueryParam(ep, schemas));
  return params;
}

function buildQueryParam(ep: ParsedEndpoint, schemas: Set<string>): string {
  const hasRequired = ep.queryParams.some((q) => q.required);
  const shape = ep.queryParams
    .map((q) => `${q.name}${q.required ? '' : '?'}: ${prefix(q.type, schemas)}`)
    .join('; ');
  return `query${hasRequired ? '' : '?'}: { ${shape} }`;
}

function buildDescriptorFields(ep: ParsedEndpoint): string[] {
  const interpolated = ep.pathParams.reduce(
    (p, param) => p.replace(`{${param.name}}`, `\${${param.name}}`),
    ep.path,
  );
  const pathExpr = ep.pathParams.length ? `\`${interpolated}\`` : `'${interpolated}'`;
  const fields = [`method: '${ep.method}'`, `path: ${pathExpr}`];
  if (ep.requestBodyType)    fields.push('body');
  if (ep.queryParams.length) fields.push('query');
  return fields;
}

/**
 * Prefixes a TypeScript type string with `Types.` when it refers to a named schema.
 * Handles unions, intersections, and arrays recursively. Single source of truth.
 */
function prefix(type: string, schemas: Set<string>): string {
  const t = type.trim();
  if (!t) return t;

  // Handle arrays first
  if (t.endsWith('[]')) {
    return `${prefix(t.slice(0, -2), schemas)}[]`;
  }

  // Handle inline objects
  if (t.startsWith('{') && t.endsWith('}')) {
    const inner = t.slice(1, -1);

    const fields = inner
      .split(/;(?![^{]*\})/) // split by semicolon not inside braces
      .map((line) => {
        const [key, val] = line.split(/:(.+)/).map((x) => x.trim());
        if (!val) return line;
        return `${key}: ${prefix(val, schemas)}`;
      })
      .join('; ');

    return `{ ${fields} }`;
  }

  // Handle parentheses recursively
  if (t.startsWith('(') && t.endsWith(')')) {
    const inner = t.slice(1, -1);
    return `(${prefix(inner, schemas)})`;
  }

  // Handle unions & intersections, taking care of parentheses
  let depth = 0;
  const parts: string[] = [];
  let current = '';
  for (let i = 0; i < t.length; i++) {
    const char = t[i];
    if (char === '(') depth++;
    if (char === ')') depth--;
    if ((char === '|' || char === '&') && depth === 0) {
      parts.push(current.trim(), char);
      current = '';
    } else {
      current += char;
    }
  }
  if (current) parts.push(current.trim());

  if (parts.length > 1) {
    return parts.map((p) => (p === '|' || p === '&' ? p : prefix(p, schemas))).join('');
  }

  // Named schema
  // Sanitize named schema references
  const safeName = t.replace(/\./g, '_');
  return schemas.has(safeName) ? `Types.${safeName}` : safeName;
}