import type { FileMap, CodegenOptions } from '../../types/openapi.ts';
import {
  tagToSegments,
  segmentsToFilePath,
  segmentsToImportVar,
} from '../utils/identifier.ts';

const NOTICE = '/* Auto-generated by ApiFoundry — do not edit */';

function endpointHeader(depth: number): string {
  const rel = depth === 0 ? '.' : Array(depth).fill('..').join('/');
  return [
    NOTICE,
    `import type { RequestDescriptor } from 'apifoundry/runtime';`,
    `import type * as Types from '${rel}/types';`,
    '',
  ].join('\n');
}

export function buildFileMap(
  typesContent: string,
  endpointsByTag: Map<string, string>,
  options: CodegenOptions,
): FileMap {
  const { sdkDir } = options;
  const files: FileMap = {};

  files[`${sdkDir}/types/index.ts`] = typesContent;

  for (const [tag, content] of endpointsByTag) {
    const segments = tagToSegments(tag);
    const depth = segments.length - 1;
    const filePath = segmentsToFilePath(segments);
    files[`${sdkDir}/${filePath}.ts`] = endpointHeader(depth) + content;
  }

  const barrelLines: string[] = [NOTICE];
  for (const tag of endpointsByTag.keys()) {
    const segments = tagToSegments(tag);
    const filePath = segmentsToFilePath(segments);
    const nsAlias = segmentsToImportVar(segments);
    barrelLines.push(`export * as ${nsAlias} from './${filePath}';`);
  }
  barrelLines.push(`export * from './types';`);
  files[`${sdkDir}/index.ts`] = barrelLines.join('\n') + '\n';

  return files;
}

export function buildApiFileContent(
  tags: string[],
  options: CodegenOptions,
): string {
  const { sdkDir } = options;

  const tagSegmentMap = new Map<string, string[]>();
  for (const tag of tags) {
    tagSegmentMap.set(tag, tagToSegments(tag));
  }

  // ── Import statements ───────────────────────────────────────────────────────
  const imports: string[] = [];
  for (const [, segments] of tagSegmentMap) {
    const varName  = segmentsToImportVar(segments);
    const filePath = segmentsToFilePath(segments);
    imports.push(`import * as ${varName} from './${sdkDir}/${filePath}';`);
  }

  // ── Build tree ──────────────────────────────────────────────────────────────
  interface TreeNode {
    _self: boolean;
    segments: string[];
    children: Map<string, TreeNode>;
  }

  const tree = new Map<string, TreeNode>();

  for (const [, segments] of tagSegmentMap) {
    let current = tree;
    for (let i = 0; i < segments.length; i++) {
      const seg: string | undefined = segments[i];
      if (seg === undefined) break;

      if (!current.has(seg)) {
        current.set(seg, { _self: false, segments: segments.slice(0, i + 1), children: new Map() });
      }
      const node: TreeNode | undefined = current.get(seg);
      if (node === undefined) break;
      if (i === segments.length - 1) node._self = true;
      current = node.children;
    }
  }

  // ── Render object body
  // CORRECT: accounts: accounts   (shorthand: just `accounts,`)
  //   TypeScript sees the module namespace type directly:
  //   { Accounts_GetAccounts: () => RD<AccountsResponse>, ... }
  //   BoundTree<T> maps each key correctly → api.accounts.Accounts_GetAccounts() ✓
  //
  // For a node that has BOTH its own endpoints AND child namespaces:
  //   manager tag exists (own endpoints) + manager/auth child exists
  //   The value at key 'manager' must be a SINGLE EndpointTree object.
  //   We build it as: { ...manager, auth: manager_auth }
  //   - ...manager spreads the own endpoint functions (EndpointFn values) ✓
  //   - auth: manager_auth passes the child module reference directly    ✓
  //   The combined object satisfies EndpointTree.

  function renderTree(nodes: Map<string, TreeNode>, indent: string): string {
    const lines: string[] = [];

    for (const [key, node] of nodes) {
      const varName = segmentsToImportVar(node.segments);
      const hasChildren = node.children.size > 0;

      if (node._self && hasChildren) {
        // Has own endpoints + child namespaces.
        // Spread own endpoints first, then add children as named keys.
        const childLines = renderChildKeys(node.children, indent + '  ');
        lines.push(`${indent}${key}: {`);
        lines.push(`${indent}  ...${varName},`);  // own endpoint functions
        lines.push(childLines);
        lines.push(`${indent}},`);
      } else if (node._self && !hasChildren) {
        // Leaf tag: just reference the module directly (NO { ...spread } wrapper).
        lines.push(`${indent}${key}: ${varName},`);
      } else {
        // Intermediate namespace (no own endpoints, only children).
        const childLines = renderTree(node.children, indent + '  ');
        lines.push(`${indent}${key}: {`);
        lines.push(childLines);
        lines.push(`${indent}},`);
      }
    }

    return lines.join('\n');
  }

  // Renders child keys for a node that has both own endpoints and children.
  // Children are always passed as direct module references (no spread wrapper).
  function renderChildKeys(children: Map<string, TreeNode>, indent: string): string {
    const lines: string[] = [];

    for (const [key, child] of children) {
      const childVar = segmentsToImportVar(child.segments);
      const hasGrandchildren = child.children.size > 0;

      if (child._self && hasGrandchildren) {
        // Child also has its own endpoints + grandchildren — recurse
        const grandchildLines = renderChildKeys(child.children, indent + '  ');
        lines.push(`${indent}${key}: {`);
        lines.push(`${indent}  ...${childVar},`);
        lines.push(grandchildLines);
        lines.push(`${indent}},`);
      } else if (child._self) {
        // Child leaf — direct reference, no spread wrapper
        lines.push(`${indent}${key}: ${childVar},`);
      } else {
        // Child is an intermediate namespace
        const grandchildLines = renderChildKeys(child.children, indent + '  ');
        lines.push(`${indent}${key}: {`);
        lines.push(grandchildLines);
        lines.push(`${indent}},`);
      }
    }

    return lines.join('\n');
  }

  const objectBody = renderTree(tree, '    ');

  const usageLines = [...tagSegmentMap.entries()]
    .slice(0, 4)
    .map(([, segs]) => ` *   api.${segs.join('.')}.*`);

  return `/**
 * API Client
 *
 * Generated once by ApiFoundry — this file is yours to configure.
 * Re-running "apifoundry generate" will NOT overwrite it.
 *
 * Usage:
${usageLines.join('\n')}
 */
import { createClient } from 'apifoundry/runtime';
${imports.join('\n')}

export const api = createClient(
  {
${objectBody}
  },
  {
    baseUrl: process.env.NEXT_PUBLIC_API_URL ?? process.env.VITE_API_URL ?? '',
  },
);

// --- Option B: Axios ----------------------------------------------------
// import { axiosInstance } from './lib/axios';
// export const api = createClient({ ... }, { axiosInstance });

// --- Option C: Custom Adapter -------------------------------------------
// import type { HttpAdapter } from 'apifoundry/runtime';
// const adapter: HttpAdapter = { execute: async (d) => { /* ... */ } };
// export const api = createClient({ ... }, { adapter });

export type Api = typeof api;
`;
}