import type { FileMap, CodegenOptions } from '../../types/openapi.ts';

const NOTICE = '/* Auto-generated by ApiFoundry — do not edit */';

/**
 * Ensures path is normalized (no leading/trailing slashes)
 */
function normalizePath(path: string): string {
  return path.replace(/^\/+|\/+$/g, '');
}

/**
 * Resolves tag into:
 *  "manager/profile" → { folder: "manager", file: "profile" }
 *  "manager"         → { folder: "manager", file: "index" }
 */
function resolveTag(tag: string): { folder: string; file: string } {
  const parts = normalizePath(tag).split('/').filter(Boolean);

  const folder = parts[0];
  const file = parts[1] ?? 'index';

  return { folder, file };
}

/**
 * Builds endpoint file header.
 * Always relative to sdkDir root.
 */
function endpointHeader(depth: number): string {
  const typesImportPath = depth === 0 ? './types' : `${'../'.repeat(depth)}types`;
  return [
    NOTICE,
    `import type { RequestDescriptor } from 'apifoundry/runtime';`,
    `import type * as Types from '${typesImportPath}';`,
    '',
  ].join('\n');
}

/**
 * Converts tag to safe folder path
 * Example:
 *   "manager/profile" → ["manager", "profile"]
 */
function tagToSegments(tag: string): string[] {
  return normalizePath(tag).split('/');
}

/**
 * "user-management" → "userManagement"
 */
function camelCase(str: string): string {
  return str.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}

/**
 * Builds full file map with nested folder support.
 *
 * Supports:
 *   manager/profile
 *   manager/profile/settings
 *   broker/auth
 *   etc.
 */
export function buildFileMap(
  typesContent: string,
  endpointsByTag: Map<string, string>,
  options: CodegenOptions,
): FileMap {
  const { sdkDir } = options;
  const files: FileMap = {};

  // ─── Types Folder ────────────────────────────────────────────
  files[`${sdkDir}/types/index.ts`] = typesContent;

  const rootExports: string[] = [];
  
  for (const [tag, content] of endpointsByTag) {
    const segments = tagToSegments(tag); // ["manager","profile"]
    const fileName = segments.pop()!;    // "profile"
    const folderPath = segments.join('/'); // "manager"

    // Final file path
    const fullPath = folderPath
      ? `${sdkDir}/${folderPath}/${fileName}.ts`
      : `${sdkDir}/${fileName}.ts`;

    // Depth = how many levels deep from sdkDir
    // Example:
    //   api/manager/profile.ts
    //   segments = ["manager"]
    //   depth = 1
    const depth = segments.length;

    files[fullPath] = endpointHeader(depth) + content;

    // Root barrel export
    const exportPath = folderPath
      ? `./${folderPath}/${fileName}`
      : `./${fileName}`;

    rootExports.push(`export * from '${exportPath}';`);
  }

  // ─── Root Barrel ────────────────────────────────────────────
  files[`${sdkDir}/index.ts`] = [
    NOTICE,
    ...rootExports,
    `export * from './types';`,
  ].join('\n');

  return files;
}

/**
 * Builds api.ts file (supports nested tag imports).
 */
// export function buildApiFileContent(
//   tags: string[],
//   options: CodegenOptions,
// ): string {
//   const { sdkDir } = options;

//   const imports: string[] = [];
//   const spreads: string[] = [];
//   const spreadsInline: string[] = [];

//   for (const tag of tags) {
//     const segments = tagToSegments(tag);
//     const fileName = segments.pop()!;
//     const folderPath = segments.join('/');
//     const varName = camelCase(fileName);

//     const importPath = folderPath
//       ? `./${sdkDir}/${folderPath}/${fileName}`
//       : `./${sdkDir}/${fileName}`;

//     imports.push(`import * as ${varName} from '${importPath}';`);
//     spreads.push(`  ...${varName},`);
//     spreadsInline.push(`...${varName}`);
//   }

//   return `/**
//  * API Client
//  *
//  * Generated once by ApiFoundry — this file is yours to configure.
//  * Re-running "apifoundry generate" will NOT overwrite it.
//  */
// import { createClient } from 'apifoundry/runtime';
// ${imports.join('\n')}

// // ─── Option A: Built-in fetch ───────────────────────────────────
// export const api = createClient(
//   {
// ${spreads.join('\n')}
//   },
//   {
//     baseUrl: process.env.NEXT_PUBLIC_API_URL ?? process.env.VITE_API_URL ?? '',
//   },
// );

// // ─── Option B: Axios ────────────────────────────────────────────
// // import { axiosInstance } from './lib/axios';
// // export const api = createClient({ ${spreadsInline.join(', ')} }, { axiosInstance });

// // ─── Option C: Custom Adapter ───────────────────────────────────
// // import type { HttpAdapter } from 'apifoundry/runtime';
// // const adapter: HttpAdapter = { execute: async (d) => { /* ... */ } };
// // export const api = createClient({ ${spreadsInline.join(', ')} }, { adapter });

// export type Api = typeof api;
// `;
// }

export function buildApiFileContent(
  tags: string[],
  options: CodegenOptions,
): string {
  const { sdkDir } = options;

  const imports: string[] = [];

  // Structure:
  // {
  //   manager: { auth: true, faq: true }
  //   admin: { auth: true }
  // }
  const tree: Record<string, Record<string, string>> = {};

  for (const tag of tags) {
    const segments = tagToSegments(tag); // ["manager","auth"]

    const root = segments[0];            // "manager"
    const child = segments[1] ?? 'index';

    if (!tree[root]) tree[root] = {};

    tree[root][child] = tag; // keep original tag for path resolution
  }

  // Generate imports
  for (const root in tree) {
    for (const child in tree[root]) {
      const importVar = `${root}_${child}`; // unique variable name

      const importPath =
        child === 'index'
          ? `./${sdkDir}/${root}`
          : `./${sdkDir}/${root}/${child}`;

      imports.push(`import * as ${importVar} from '${importPath}';`);
    }
  }

  // Build nested object string
  const nestedObject: string[] = [];

  for (const root in tree) {
    nestedObject.push(`    ${root}: {`);

    for (const child in tree[root]) {
      const importVar = `${root}_${child}`;
      nestedObject.push(`      ...${importVar},`);
    }

    nestedObject.push(`    },`);
  }

  return `/**
 * API Client
 *
 * Generated once by ApiFoundry — this file is yours to configure.
 * Re-running "apifoundry generate" will NOT overwrite it.
 */
import { createClient } from 'apifoundry/runtime';
${imports.join('\n')}

// ─── Option A: Built-in fetch ───────────────────────────────────
export const api = createClient(
  {
${nestedObject.join('\n')}
  },
  {
    baseUrl: process.env.NEXT_PUBLIC_API_URL ?? process.env.VITE_API_URL ?? '',
  },
);

// ─── Option B: Axios ────────────────────────────────────────────
// import { axiosInstance } from './lib/axios';
// export const api = createClient({ ... }, { axiosInstance });

// ─── Option C: Custom Adapter ───────────────────────────────────
// import type { HttpAdapter } from 'apifoundry/runtime';
// const adapter: HttpAdapter = { execute: async (d) => { /* ... */ } };
// export const api = createClient({ ... }, { adapter });

export type Api = typeof api;
`;
}