import type { ParsedSchema } from '../../types/openapi.ts';

const NOTICE = '/* Auto-generated by ApiFoundry — do not edit */';

export function generateTypes(schemas: ParsedSchema[]): string {
  if (!schemas || schemas.length === 0) return `${NOTICE}\n\n// No schemas found.\n`;

  return [NOTICE, '', ...schemas.map(toDeclaration)].join('\n');
}

function toDeclaration(s: ParsedSchema): string {
  if (s.enumValues?.length) return toEnumType(s);
  if (s.type === 'object' && s.properties) return toInterface(s);
  if (s.type?.endsWith('[]')) return `export type ${sanitizeName(s.name)} = ${sanitizeTypeReference(s.type)};\n`;
  return `export type ${sanitizeName(s.name)} = ${sanitizeTypeReference(s.type ?? 'any')};\n`;
}

function toEnumType(s: ParsedSchema): string {
  const union = s.enumValues!
    .map((v) => (typeof v === 'string' ? `'${v}'` : v))
    .join(' | ');
  return `export type ${sanitizeName(s.name)} = ${union};\n`;
}

function toInterface(s: ParsedSchema): string {
  const safeName = sanitizeName(s.name);
  const props = Object.entries(s.properties!).map(([k, v]) => {
    const optional = !s.required?.includes(k);
    return `  ${k}${optional ? '?' : ''}: ${sanitizeTypeReference(v)};`;
  });
  return `export interface ${safeName} {\n${props.join('\n')}\n}\n`;
}

function sanitizeName(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, '_');
}

/**
 * Recursively sanitize type references.
 */
function sanitizeTypeReference(type: string): string {
  const t = type.trim();
  if (!t) return t;

  // If it's a primitive or string literal, leave as-is
  if (/^'.*'$/.test(t) || /^(string|number|boolean|any|null|undefined)$/.test(t)) {
    return t;
  }

  // Array types (e.g., tax_id_[])
  if (t.endsWith('[]')) {
    return `${sanitizeTypeReference(t.slice(0, -2))}[]`;
  }

  // Inline object type (e.g., { foo?: string; bar: number })
  if (t.startsWith('{') && t.endsWith('}')) {
    const inner = t.slice(1, -1)
      .split(/;(?![^{]*\})/) // top-level semicolons
      .map((line) => {
        const [key, val] = line.split(/:(.+)/).map((x) => x.trim());
        if (!val) return line;
        return `${key}: ${sanitizeTypeReference(val)}`;
      })
      .join('; ');
    return `{ ${inner} }`;
  }

  // Union or intersection types
  if (t.includes('|') || t.includes('&')) {
    return t
      .split(/(\||&)/)
      .map((part) => (part === '|' || part === '&' ? part : sanitizeTypeReference(part.trim())))
      .join('');
  }

  // Otherwise, return as-is (preserves underscores, no Types prefix)
  return t.replace(/\./g, '_');
}