import { describe, it, expect } from 'vitest';
import { generateEndpoints } from '../../../src/codegen/generators/endpoint-generator.ts';
import { parsePaths }        from '../../../src/codegen/parsers/path-parser.ts';
import { parseSchemas }      from '../../../src/codegen/parsers/schema-parser.ts';
import type { OpenAPIV3 } from 'openapi-types';
import petstoreSpec from '../../fixtures/petstore.json';

const spec        = petstoreSpec as unknown as OpenAPIV3.Document;
const schemaNames = parseSchemas(spec).map((s) => s.name);
const endpoints   = parsePaths(spec);

function generateAll(): string {
  return generateEndpoints(endpoints, schemaNames);
}

// ─────────────────────────────────────────────────────────────────────────────
// Structure
// ─────────────────────────────────────────────────────────────────────────────

describe('generateEndpoints — output structure', () => {
  const output = generateAll();

  // Fix 1: generateEndpoints() returns raw endpoint code only.
  // The NOTICE comment is prepended by file-map-builder.ts (endpointHeader)
  // when writing the file to disk. Asserting it here was wrong.
  it('exports every pet endpoint as a const', () => {
    expect(output).toContain('export const Pet_addPet');
    expect(output).toContain('export const Pet_updatePet');
    expect(output).toContain('export const Pet_getPetById');
    expect(output).toContain('export const Pet_deletePet');
    expect(output).toContain('export const Pet_findPetsByStatus');
  });

  it('exports every store endpoint as a const', () => {
    expect(output).toContain('export const Store_getInventory');
    expect(output).toContain('export const Store_placeOrder');
    expect(output).toContain('export const Store_getOrderById');
  });

  it('exports every user endpoint as a const', () => {
    expect(output).toContain('export const User_createUser');
    expect(output).toContain('export const User_loginUser');
    expect(output).toContain('export const User_getUserByName');
    expect(output).toContain('export const User_deleteUser');
  });

  it('every export returns RequestDescriptor', () => {
    const lines = output.split('\n').filter((l) => l.includes('export const'));
    expect(lines.length).toBeGreaterThan(0);
    for (const line of lines) {
      expect(line).toContain('RequestDescriptor');
    }
  });

  it('includes JSDoc with HTTP method and path', () => {
    expect(output).toContain('/** POST /pet */');
    expect(output).toContain('/** PUT /pet */');
    expect(output).toContain('/** GET /pet/findByStatus */');
    expect(output).toContain('/** GET /pet/{petId} */');
    expect(output).toContain('/** DELETE /pet/{petId} */');
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// The NOTICE is added at the file level by file-map-builder, NOT generateEndpoints
// ─────────────────────────────────────────────────────────────────────────────

describe('generateEndpoints — NOTICE is file-level concern', () => {
  it('output does NOT contain the auto-generated NOTICE (that is added by buildFileMap)', () => {
    const output = generateAll();
    // The NOTICE "/* Auto-generated by ApiFoundry — do not edit */" is injected
    // by endpointHeader() in file-map-builder.ts when assembling the final file.
    // generateEndpoints() returns only the endpoint function bodies.
    expect(output).not.toContain('Auto-generated by ApiFoundry');
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Type references
// ─────────────────────────────────────────────────────────────────────────────

describe('generateEndpoints — type references', () => {
  const output = generateAll();

  it('prefixes known schema names with Types.', () => {
    expect(output).toContain('RequestDescriptor<Types.Pet>');
    expect(output).toContain('RequestDescriptor<Types.Order>');
    expect(output).toContain('RequestDescriptor<Types.User>');
  });

  it('uses "any" for endpoints without a response schema', () => {
    expect(output).toContain('RequestDescriptor<any>');
  });

  it('uses primitive type for string response (User_loginUser)', () => {
    expect(output).toContain('RequestDescriptor<string>');
  });

  it('uses array type for array response (Pet_findPetsByStatus)', () => {
    expect(output).toContain('RequestDescriptor<Types.Pet[]>');
  });

  it('prefixes request body with Types.', () => {
    expect(output).toContain('body: Types.Pet');
    expect(output).toContain('body: Types.Order');
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Path parameters
// ─────────────────────────────────────────────────────────────────────────────

describe('generateEndpoints — path parameters', () => {
  const output = generateAll();

  it('Pet_getPetById has petId: number argument', () => {
    expect(output).toContain('petId: number');
  });

  it('Pet_getPetById uses template literal for path interpolation', () => {
    expect(output).toContain('`/pet/${petId}`');
  });

  it('User_getUserByName has username: string argument', () => {
    expect(output).toContain('username: string');
    expect(output).toContain('`/user/${username}`');
  });

  it('Store_getOrderById has orderId: number argument', () => {
    expect(output).toContain('orderId: number');
    expect(output).toContain('`/store/order/${orderId}`');
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Query parameters
// ─────────────────────────────────────────────────────────────────────────────

describe('generateEndpoints — query parameters', () => {
  const output = generateAll();

  it('Pet_findPetsByStatus has required query param (no ?)', () => {
    expect(output).toMatch(/status:\s*'available' \| 'pending' \| 'sold'/);
  });

  it('User_loginUser has optional query params (? suffix)', () => {
    expect(output).toContain('username?:');
    expect(output).toContain('password?:');
  });

  it('User_loginUser optional query object has ? suffix', () => {
    expect(output).toContain('query?:');
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Empty input
// ─────────────────────────────────────────────────────────────────────────────

describe('generateEndpoints — empty input', () => {
  it('returns a comment for empty array', () => {
    const result = generateEndpoints([], []);
    expect(result).toContain('No endpoints');
  });
});