import { describe, it, expect } from 'vitest';
import { generateTypes } from '../../../src/codegen/generators/type-generator.ts';
import { parseSchemas }  from '../../../src/codegen/parsers/schema-parser.ts';
import type { OpenAPIV3 } from 'openapi-types';
import petstoreSpec from '../../fixtures/petstore.json';

const spec = petstoreSpec as unknown as OpenAPIV3.Document;

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

function typesFromSpec(s: OpenAPIV3.Document): string {
  return generateTypes(parseSchemas(s));
}

// ─────────────────────────────────────────────────────────────────────────────
// Empty / missing schemas
// ─────────────────────────────────────────────────────────────────────────────

describe('generateTypes — empty input', () => {
  it('returns a no-schemas comment for empty array', () => {
    const result = generateTypes([]);
    expect(result).toContain('No schemas found');
  });

  it('always includes the auto-generated notice', () => {
    expect(generateTypes([])).toContain('Auto-generated by ApiFoundry');
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Petstore — output structure
// ─────────────────────────────────────────────────────────────────────────────

describe('generateTypes — Petstore output', () => {
  const output = typesFromSpec(spec);

  it('exports every Petstore schema', () => {
    expect(output).toContain('export interface Pet');
    expect(output).toContain('export interface Order');
    expect(output).toContain('export interface User');
    expect(output).toContain('export interface Category');
    expect(output).toContain('export interface Tag');
    expect(output).toContain('export interface ApiResponse');
  });

  it('marks required fields as non-optional in Pet', () => {
    // name and photoUrls are required — must NOT have ?
    expect(output).toMatch(/name:\s*string/);
    expect(output).toMatch(/photoUrls:\s*string\[\]/);
  });

  it('marks optional fields with ? in Pet', () => {
    // id, category, tags, status are optional
    expect(output).toMatch(/id\?:/);
    expect(output).toMatch(/category\?:/);
    expect(output).toMatch(/status\?:/);
  });

  it('generates enum union type for Order status', () => {
    expect(output).toContain("'placed'");
    expect(output).toContain("'approved'");
    expect(output).toContain("'delivered'");
  });

  it('uses Types reference for $ref properties', () => {
    // category in Pet should reference Category
    expect(output).toContain('Category');
  });

  it('generates array type for photoUrls', () => {
    expect(output).toContain('string[]');
  });

  it('output is valid TypeScript (no unbalanced braces)', () => {
    const opens  = (output.match(/\{/g) ?? []).length;
    const closes = (output.match(/\}/g) ?? []).length;
    expect(opens).toBe(closes);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Enum-only schema
// ─────────────────────────────────────────────────────────────────────────────

describe('generateTypes — enum schema', () => {
  const enumSpec: OpenAPIV3.Document = {
    openapi: '3.0.0',
    info: { title: 'T', version: '1' },
    paths: {},
    components: {
      schemas: {
        OrderStatus: { type: 'string', enum: ['placed', 'approved', 'delivered'] },
        Priority:    { type: 'integer', enum: [1, 2, 3] },
      },
    },
  };

  const output = generateTypes(parseSchemas(enumSpec));

  it('generates string union for string enum', () => {
    expect(output).toContain("export type OrderStatus = 'placed' | 'approved' | 'delivered'");
  });

  it('generates numeric union for integer enum', () => {
    expect(output).toContain('export type Priority = 1 | 2 | 3');
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Schema name sanitisation
// ─────────────────────────────────────────────────────────────────────────────

describe('generateTypes — name sanitisation', () => {
  it('replaces dots in schema names with underscores', () => {
    const dotSpec: OpenAPIV3.Document = {
      openapi: '3.0.0',
      info: { title: 'T', version: '1' },
      paths: {},
      components: {
        schemas: {
          'Login.Response': {
            type: 'object',
            properties: { token: { type: 'string' } },
          },
        },
      },
    };
    const output = generateTypes(parseSchemas(dotSpec));
    expect(output).toContain('Login_Response');
    expect(output).not.toContain('Login.Response');
  });
});