// import type { ParsedSchema } from './parse-schemas.ts';

// export function generateTypes(schemas: ParsedSchema[]): string {
//   return schemas.map(schema => {
//     return `export interface ${schema.name} ${schema.typeContent}`;
//   }).join('\n\n');
// }



// src/core/generate-types.ts

import type { ParsedSchema } from './parse-schemas.ts';

function resolveEnum(values: unknown[]): string {
  return values
    .map(v =>
      typeof v === 'string'
        ? `'${v}'`
        : JSON.stringify(v),
    )
    .join(' | ');
}

export function generateTypes(
  schemas: ParsedSchema[],
): string {
  return `
/* Auto-generated by ApiFoundry */

${schemas.map(generateSingleType).join('\n')}
`;
}

function generateSingleType(schema: ParsedSchema): string {
  const {
    name,
    type,
    properties,
    required,
    enumValues,
  } = schema;

  // ✅ ENUM
  if (enumValues && enumValues.length > 0) {
    return `
export type ${name} = ${resolveEnum(enumValues)};
`;
  }

  // ✅ OBJECT
  if (type === 'object' && properties) {
    const props = Object.entries(properties)
      .map(([key, value]) => {
        const isRequired = required?.includes(key);
        return `  ${key}${isRequired ? '' : '?'}: ${value};`;
      })
      .join('\n');

    return `
export interface ${name} {
${props}
}
`;
  }

  // ✅ ARRAY ROOT SCHEMA
  if (type?.endsWith('[]')) {
    return `
export type ${name} = ${type};
`;
  }

  // ✅ PRIMITIVE ALIAS (string, number, boolean)
  return `
export type ${name} = ${type ?? 'any'};
`;
}