/* Auto-generated by ApiFoundry */

/**
 * Transport-agnostic HTTP adapter interface
 */
export interface HttpAdapter {
  request<T>(options: RequestOptions): Promise<ApiResponse<T>>;
}

/**
 * Request options for HTTP calls
 */
export interface RequestOptions {
  method: string;
  url: string;
  query?: Record<string, any>;
  body?: any;
  headers?: Record<string, string>;
}

/**
 * Unified API response structure
 */
export interface ApiResponse<T> {
  success: boolean;
  data: T | null;
  error: string | null;
  status: number;
}